spring.application.name=multidb

server.port=9093

spring.datasource.employee.url=jdbc:mysql://localhost:3306/employeedb?useSSL=false&serverTimezone=UTC
spring.datasource.employee.username=root
spring.datasource.employee.password=uday@2026
spring.datasource.employee.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.customer.url=jdbc:mysql://localhost:3306/customer_db?useSSL=false&serverTimezone=UTC
spring.datasource.customer.username=root
spring.datasource.customer.password=uday@2026
spring.datasource.customer.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


