spring.application.name=multiDB1

# ===============================
# PRODUCT DATABASE
# ===============================

app.datasource.product.url=jdbc:mysql://localhost:3306/product_db
app.datasource.product.username=root
app.datasource.product.password=uday@2026
app.datasource.product.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# CUSTOMER DATABASE
# ===============================

app.datasource.customer.url=jdbc:mysql://localhost:3306/customer_db
app.datasource.customer.username=root
app.datasource.customer.password=uday@2026
app.datasource.customer.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
